name: Lint Python and C++

on:
  # Trigger the workflow on push or pull request
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-python:
    name: Lint Python Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Set your Python version

      - name: Install dependencies
        run: |
          pip3 install pylint

      - name: Run Pylint
        run: |
          pylint scripts/  # Replace with your Python directory

  lint-cpp:
    name: Lint C++ Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck

      - name: Run Cppcheck
        run: |
          cppcheck --enable=all --inconclusive --error-exitcode=1 src/ include/ # Replace with your C++ directory

